# Generated by Django 4.2.5 on 2023-09-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='insta',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
