# Generated by Django 4.2.5 on 2023-09-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_insta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='job',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telephone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='prenom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
