# Generated by Django 4.2.5 on 2023-11-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_images',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profil_images',
            field=models.ImageField(default='', upload_to='profil_images/'),
            preserve_default=False,
        ),
    ]
