# Generated by Django 4.2.5 on 2023-11-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_profile_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nouveaux_messages',
            field=models.BooleanField(default=False),
        ),
    ]
