# Generated by Django 4.2.5 on 2023-11-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_nouveaux_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nouveaux_messages',
            new_name='nouveau_message',
        ),
    ]
