# Generated by Django 4.2.5 on 2023-11-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_nouveau_message_customuser_lu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lu',
        ),
    ]
