# Generated by Django 4.2.5 on 2023-10-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_review_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='color',
            field=models.CharField(default='#111111', max_length=7),
        ),
    ]
