# Generated by Django 4.2.5 on 2023-10-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_review_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
