# Generated by Django 4.2.5 on 2023-10-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_review_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='bio',
            field=models.TextField(max_length=350),
        ),
    ]
