# Generated by Django 4.2.5 on 2023-10-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_review_bio_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='bio',
        ),
    ]
