# Generated by Django 4.2.5 on 2023-10-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_message_message_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
