# Generated by Django 4.2.5 on 2023-11-06 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_message_privee_boitedereception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boitedereception',
            name='messages',
            field=models.ManyToManyField(to='main.message'),
        ),
        migrations.AlterField(
            model_name='boitedereception',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message_privee',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
