# Generated by Django 4.2.5 on 2023-11-17 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_envoyer_message_delete_message_privee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boitedereception',
            name='messages',
        ),
        migrations.AddField(
            model_name='boitedereception',
            name='conversations',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boitedereception',
            name='last_message_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boitedereception',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
