# Generated by Django 4.2.5 on 2023-11-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_boitedereception_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoyer_message',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
