# Generated by Django 4.2.5 on 2023-11-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_envoyer_message_lu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envoyer_message',
            name='lu',
        ),
    ]
