# Generated by Django 4.2.5 on 2023-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_envoyer_message_lu'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoyer_message',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
