# Generated by Django 4.2.5 on 2023-12-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_envoyer_message_lu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=15)),
                ('cheveux', models.CharField(max_length=15)),
                ('taille', models.IntegerField(max_length=0)),
                ('tache_rousseur', models.BooleanField(default=False)),
                ('lunette', models.BooleanField(default=False)),
                ('bijoux', models.BooleanField(default=False)),
                ('yeux', models.CharField(max_length=15)),
            ],
        ),
    ]
