# Generated by Django 4.2.5 on 2023-12-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_recherche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=15)),
                ('cheveux', models.CharField(max_length=15)),
                ('taille', models.IntegerField(default=0)),
                ('tache_rousseur', models.BooleanField(default=False)),
                ('lunettes', models.BooleanField(default=False)),
                ('bijoux', models.BooleanField(default=False)),
                ('yeux', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Recherche',
        ),
    ]
