# Generated by Django 4.2.5 on 2023-12-01 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_detail_delete_recherche'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.User'),
            preserve_default=False,
        ),
    ]
